
export const systemTermsData = [
  {
    "chinese_term": "侧护栏控制器开关",
    "english_term": "Caregiver/Patient SideRail Control On/Off",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "信息帮助",
    "english_term": "Information/Help",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "帮助",
    "english_term": "Help",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "序号、按键图示、动作、按键说明",
    "english_term": "No.\\ Button Diagram \\ Motion \\ Instruction",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "重量清零",
    "english_term": "Zeroing",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "清除历史的体重数据，不同患者使用前需进行历史数据清除",
    "english_term": "Clear historical weight data, different patients need to clear historical data before use.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "体重测量",
    "english_term": "Weighing",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "点击进行称重",
    "english_term": "Click to weigh",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "增减物品",
    "english_term": "Hold Mode",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "按下“添减物品“按键，此时可在床上添减物品，不影响患者差重，添减完毕后点击“结束添减物品”",
    "english_term": "Hold Mode must be used only when the weights are stabilized. It allows attaching or removing bed accessories without changing the weight.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "新病人",
    "english_term": "New Patient",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "清除上一名患者的体重数据，新患者卧床前需进行清除，一边记录患者体重变化",
    "english_term": "Clear the weight data of the previous patient before the use for new patient.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "称量精度",
    "english_term": "Weighing Precision",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "点击图标按键可切换10g/100g精度，显示为蓝色时即为当时精度",
    "english_term": "Click the icon button to switch between 10g/100g precision, and the current precision is displayed in blue",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "趋势图",
    "english_term": "Weight Tracker",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "可查看当前患者的体重趋势图",
    "english_term": "Weight Tracker can be viewed",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "药物计算器",
    "english_term": "Calculating",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "输入药物用量系数，得到此次患者给药剂量",
    "english_term": "Enter the drug dosage coefficient to obtain the dosage for this patient's medication",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "体重指数计算器",
    "english_term": "Enter the dosage coefficient to obtain the dosage for this patient's medication",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "输入患者身高，得到此时患者的体重指数（BMI）",
    "english_term": "Enter the patient's height to obtain their body mass index (BMI) at this time",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "背板、腿板放平；实时显示床面离地高度，到达此体位后开始计时",
    "english_term": "Adjust the bed surface to a flat position and set the height to an appropriate level. Record the duration of time spent at STEP 0",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "背板抬起至45°形成半卧位；实时显示背板角度，到达此体位后开始计时",
    "english_term": "Adjust the bed surface to a flat position and set the height to an appropriate level, then raise the backrest to 45°. Record the duration of time spent at STEP 1",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "背板退回水平位并且腿板上抬至45°，过程中背板与腿板保持135°夹角；实时显示大腿板角度，到达此体位后开始计时",
    "english_term": "Maintain the appropriate height with the backrest and thighrest/calfrest at a 135° angle. After raising the thighrest/calfrest to 45° and flattening the backrest, record the duration of time spent at STEP 2",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "CO输入",
    "english_term": "CO Input",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "按下输入图标，弹出数字键盘弹窗，在数字键盘中输入心输出量",
    "english_term": "Press the input button to bring up a numeric keypad pop-up window, and enter the cardiac output on the numeric keypad",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "HOB 关",
    "english_term": "HOB ON/OFF",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "躁动提醒关",
    "english_term": "Agitation Alert ON/OFF",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "离床提醒关",
    "english_term": "Bed Exit Alert ON/OFF",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "HOB背板抬高语音提示开关，打开①后语音提示当前角度是否处于30-45°之间",
    "english_term": "HOB: The backrest angle can be set to be checked every X hours to monitor if the angle is between 30° and 45°",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "患者躁动提示开关，打开②后当患者处于躁动状态，将进行蜂鸣声报警",
    "english_term": "Agitation alert: The bed detects the patient's movement status. If the patient shows signs of agagitation, the system will alert the caregiver.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "患者离床提示开关，打开③后当患者离床/坠床，将进行蜂鸣声报警",
    "english_term": "Bed Exit Alert: The bed monitors the patient's exit status. If the patient is attempting to exit the bed, the system will alert the caregiver.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "交流电通电指示灯",
    "english_term": "Ac Power on Indicator",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "（灯亮即已通电）",
    "english_term": "The power is on when the light comes on.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "控制器指示灯",
    "english_term": "Controller Indicator/Siderail Indicator Light",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "控制器开关",
    "english_term": "Controller On/Off / Siderail On/Off Button",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "用于激活或关闭控制器功能",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "一键体位功能",
    "english_term": "One-Button Position",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "一键CPR位",
    "english_term": "One-Button CPR Position",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "一键检查位",
    "english_term": "One-Button Examination Position",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "一键心脏椅位",
    "english_term": "One-Button Cardiac chair Position",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "一键FOWLER位",
    "english_term": "One-Button FOWLER’s Position",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "一键特氏位",
    "english_term": "One-Button Trendelenburg Position",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "护栏控制器锁定指示灯",
    "english_term": "Siderail Controller Lock Indicator",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "点击按键，指示灯熄灭，可将其上方对应的护栏控制器功能锁定，防止病人误操作",
    "english_term": "Press the button and the applicable indicator light turns off to let you know that the function is locked out.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "护栏板升降",
    "english_term": "Siderail Adjustment",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "升起：握住侧护栏板向上拉，拉到最大高度后向内轻推，当听到“咔嗒”声时，代表锁定完毕。可向外拉动护栏，确认是否锁定牢固。",
    "english_term": "To Raise the Siderail:Hold the siderail and pull it upward.Push inward after reaching the maximum height. A \"click\" sound indicates it is locked. Pull the rail outward to confirm it is securely locked.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "降下：握住侧护栏板扶手位向内轻推，同时将把手往外轻拉，铰链解锁后轻提护栏。",
    "english_term": "To Lower the Siderail:Grasp the release handle and push up,Lower the siderail.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "脚踏控制器",
    "english_term": "Foot Controller",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "持续踩踏，长提持续执行对应功能，松开即停止。",
    "english_term": "Continuously step on and lift to execute the corresponding function, release to stop.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "备注：若同时踩下同侧两个按键，按以下优先级执行：整体下降＞特氏位＞整体上升",
    "english_term": "Note: If both buttons on the same side are pressed at the same time, the following priority should be followed: Bed down>Trendelenburg position>Bed up",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "夜灯开关",
    "english_term": "Night Light Switch",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "中央控制器（可选配液晶控制器）",
    "english_term": "Central Controller (optional: LCD controller)",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "电控操作方法－体位调节界面",
    "english_term": "Electric Control Operation Interface : Bed Position",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "电控操作方法－一键体位调节界面",
    "english_term": "Electric Control Operation Interface: One -Button Position",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "电控操作方法-称重调节界面",
    "english_term": "Electric Control Operation Interface: Scale",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "电控操作方法－监测提示",
    "english_term": "Electric Control Operation Interface: Alert",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "电控操作方法-PLR体位调节页面（实现被动抬腿功能）",
    "english_term": "Electric Control Operation Interface: PLR Position",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "大腿板升降",
    "english_term": "Thighrest Up/Down",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "小腿板升降",
    "english_term": "Calfrest UP/Down",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "电量提示",
    "english_term": "Battery Level",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "中央控制器开关",
    "english_term": "Central Controller On/Off",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "开机",
    "english_term": "Power On",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "连接交流电源，按照急停开关红色按钮上的箭头指示方向旋转按钮，急停开关弹出，病床可进行操作。",
    "english_term": "Plug the bed into the power supply. Turn the red central stop switch in the direction indicated by the arrow. Once the button pops out, the bed is ready for operation.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "关机",
    "english_term": "Power Off",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "按下急停开关红色按钮，病床的电源切断，停止床体所有动作。",
    "english_term": "Press the red central stop switch to cut off the power supply. All bed functions will be disabled.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "X光片盒",
    "english_term": "X-ray Cassette",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "取下床头板或抬起背板，握住图示把手上提解锁片盒，拉出X光片盒，放入X光片对准位置，推入片盒自动锁定即可完成拍片。",
    "english_term": "Remove the headboard or raise the back section, grasp the handle, pull up to unlock the cassette, pull out the X-ray cassette, place the X-ray in the correct position, and push the cassette back in to lock it and complete the X-ray operation.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "手动CPR",
    "english_term": "CPR Control",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "向外拉动CPR扣手，可迅速将背板放置水平位置（确保床体下方没有障碍物，防止夹伤事件）。",
    "english_term": "Pull and hold the CPR handle until the bed head sections are flat. (Ensure that there are no body parts between any movable parts of the bed)",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "转运使用",
    "english_term": "Transport the Patient",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "床体内置电源，直接拔出电源插头，无需操作急停开关，可在转运期间正常使用。",
    "english_term": "The bed has an automatic battery backup feature. When AC power is not supplied to the bed and there is sufficient battery power, the battery allows the bed’s functions to continue.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "床体延伸",
    "english_term": "Bed Length Adjustment",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "反手握住床尾下方的把手，如图所示，直接上提拉出即可完成床体延伸。",
    "english_term": "Hold the handle under the foot of the bed, as shown in the picture, and lift it upward to extend the bed.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "中控制动系统",
    "english_term": "Brake and Steer Controls",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "可控制床体刹车、万向、直行。",
    "english_term": "There are three positions:Brake,Neutral,Steer.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "护栏控制器",
    "english_term": "Caregiver/Patient SideRail Control",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "按下控制开关，控制指示灯亮起，即可操作各功能。",
    "english_term": "Press the control button. When the control indicator lights up, all functions can be operated.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "腿板升降",
    "english_term": "Thighrest(Calfrest) Up/Down",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "背板升降",
    "english_term": "Backrest Up/Down",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "整体升降",
    "english_term": "Bed Up/Down",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "用于激活或关闭控制器功能",
    "english_term": "Used to activate or deactivate the controller functions.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "当控制器处于激活状态时，灯就会亮起",
    "english_term": "Lights up when the controller is active.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "无该功能",
    "english_term": "Not Available",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "病人呼叫开关",
    "english_term": "Nurse Call",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "允许患者拨打电话或发出求助请求",
    "english_term": "Allows patients to send a call or request for assistance.",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "中央控制器",
    "english_term": "Central Controller",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "背腿联动",
    "english_term": "Backrest/Thighrest/Calfrest Up/Down",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "后倾（头低脚高）",
    "english_term": "Trendelenburg",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  },
  {
    "chinese_term": "前倾（头高脚低）",
    "english_term": "Antitrendelenburg",
    "pinyin_full": "",
    "pinyin_first": "",
    "category": "",
    "note": "",
    "usage_scenario": "",
    "root_analysis": "",
    "mistranslation_warning": [],
    "related_terms": []
  }
];
